DFXswiss/services

src/screens/sell.screen.tsx
- draft because it is no net yet clear if and how we want to display min fee for cryptos as the current approach looked weird
=> [DEV-1494] added sell fee (WIP min fee display)

src/api/contexts/dfx.context.tsx, src/api/contexts/user.context.tsx, src/screens/buy/payment.screen.tsx, src/screens/home.screen.tsx, src/screens/profile.screen.tsx, src/screens/sell.screen.tsx
* [NO-TASK] various small changes
* [NO-TASK] added api error message to popup
=> [NO-TASK] various small changes (#24)

src/config/feature-tree.ts
achtung ich habe auch wallet = bitbox verwendet, weiss nicht ob das funktioniert.
=> onlybitbox page eingebaut

package-lock.json, package.json, src/components/home/connect-hint.tsx, src/components/layout.tsx, src/components/navigation.tsx, src/components/payment/add-bank-account.tsx, src/config/feature-tree.ts, src/contexts/app-handling.context.tsx, src/contexts/wallet.context.tsx, src/hooks/resize-observer.hook.ts, src/screens/buy.screen.tsx, src/screens/error.screen.tsx, src/screens/home.screen.tsx, src/screens/profile.screen.tsx, src/screens/sell.screen.tsx, src/translations/languages/de.json, src/util/utils.ts
=> Revert "Revert "Alby + various improvements/fixes""

src/components/home/wallet/connect-trezor.tsx, src/hooks/wallets/trezor.hook.ts
Improvement in the selection of addresses to avoid multiple display of the popup window. The popup is now displayed once and 10 addresses are loaded.
=> [DEV-1922] trezor improvement

src/hooks/tx-helper.hook.ts, src/hooks/wallets/wallet-connect.hook.ts
* [DEV-1754] sell with wallet connect
* [DEV-1754] remove logs
* [DEV-1754] refactoring
* [DEV-1754] remove await
---------
Co-authored-by: Kolibri <>
[DEV-1754]: https://dfxswiss.atlassian.net/browse/DEV-1754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1754]: https://dfxswiss.atlassian.net/browse/DEV-1754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1754]: https://dfxswiss.atlassian.net/browse/DEV-1754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1754]: https://dfxswiss.atlassian.net/browse/DEV-1754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-1754] sell with wallet connect (#228)

package-lock.json, package.json, src/App.tsx, src/components/payment/giro-code.tsx, src/components/payment/payment-information.tsx, src/config/labels.ts, src/contexts/app-handling.context.tsx, src/screens/buy.screen.tsx, src/screens/limit.screen.tsx, src/screens/sell.screen.tsx, src/screens/support-issue.screen.tsx, src/screens/swap.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
=> Support issues, various improvements/fixes

package-lock.json, package.json, src/App.tsx, src/components/kyc-hint.tsx, src/components/navigation.tsx, src/contexts/app-handling.context.tsx, src/hooks/wallets/wallet-connect.hook.ts, src/index-widget.tsx, src/screens/buy-info.screen.tsx, src/screens/buy.screen.tsx, src/screens/home.screen.tsx, src/screens/sell-info.screen.tsx, src/screens/sell.screen.tsx, src/screens/support-issue.screen.tsx, src/screens/swap.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
[DEV-2508] Added general support issue UI
[DEV-2570] enable standalone services login module
[DEV-2508]: https://dfxswiss.atlassian.net/browse/DEV-2508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2570]: https://dfxswiss.atlassian.net/browse/DEV-2570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2508] [DEV-2570] 

README.md, package-lock.json, package.json, src/App.tsx, src/components/navigation.tsx, src/config/feature-tree.ts, src/contexts/app-handling.context.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
* [DEV-2434] Integrated swap
* [DEV-2423] Added swap link
* [DEV-2423] Swap invisible
[DEV-2434]: https://dfxswiss.atlassian.net/browse/DEV-2434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2423]: https://dfxswiss.atlassian.net/browse/DEV-2423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2423]: https://dfxswiss.atlassian.net/browse/DEV-2423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2434] Swap (#250)

src/contexts/app-handling.context.tsx, src/index-widget.tsx, src/screens/buy.screen.tsx, src/screens/swap.screen.tsx
* [DEV-2656] add prop to hide target address selection
* apply hideTargetSelection to swap screen + small parameter name fix
[DEV-2656]: https://dfxswiss.atlassian.net/browse/DEV-2656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2656] add prop to hide target address selection (#258)

src/contexts/app-handling.context.tsx, src/hooks/store.hook.ts
* [DEV-2663] Added TODOs
* store query params in local storage as JSON
* improve logic
---------
[DEV-2663]: https://dfxswiss.atlassian.net/browse/DEV-2663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2663] params to local storage (#261)

package-lock.json, package.json, src/hooks/tx-helper.hook.ts, src/hooks/wallets/wallet-connect.hook.ts, src/wagmi.config.ts
* [DEV-2625] implement WalletConnect hook using @wagmi/core
* removed unused variables
* integrate getBalance for WalletConnect
* add error handling + fix small review issues
* remove unused var + simplify error handling
* solve react-scripts dependency conflicts
---------
[DEV-2625]: https://dfxswiss.atlassian.net/browse/DEV-2625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2625] walletconnect multichain support (#270)

package-lock.json, package.json, src/components/exchange-rate.tsx, src/components/payment/qr-copy.tsx, src/screens/buy.screen.tsx, src/screens/sell-info.screen.tsx, src/screens/sell.screen.tsx, src/screens/swap.screen.tsx, src/screens/transaction.screen.tsx, src/static/assets/path-arrow.svg, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [NO-TASK] Fixed error handling
- [DEV-2467] price derivation 
- [DEV-2568] Dubai transactions 
[DEV-2467]: https://dfxswiss.atlassian.net/browse/DEV-2467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2568]: https://dfxswiss.atlassian.net/browse/DEV-2568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2467] [DEV-2568][NO-TASK]

package-lock.json, package.json, src/App.tsx, src/components/exchange-rate.tsx, src/screens/buy-failure.screen.tsx, src/screens/kyc.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
[DEV-2697] Fixed merged user handling
[DEV-2690] Card payment failure screen
[DEV-2697]: https://dfxswiss.atlassian.net/browse/DEV-2697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2690]: https://dfxswiss.atlassian.net/browse/DEV-2690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2697] [DEV-2690] 

src/screens/transaction.screen.tsx
* refetch transaction every 10 sec
* fix useEffect dependencies
=> [DEV-2616] Auto-refresh transaction status screen (#279)

package-lock.json, package.json, src/components/exchange-rate.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
=> [DEV-1434] Display network start fee

src/contexts/app-handling.context.tsx, src/contexts/settings.context.tsx, src/index-widget.tsx, src/screens/kyc.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2806]  place KYC steps in expandable row
- [NO-TASK] Add new parameter `auto-start` to automatically resume KYC process at next step
[DEV-2806]: https://dfxswiss.atlassian.net/browse/DEV-2806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2806] KYC level layout

src/contexts/window.context.tsx, src/screens/swap.screen.tsx, src/util/utils.ts
- fix blankedAddress overflow
- group receiver addresses by blockchain in swap screen
=> [NO-TASK] small improvements

src/contexts/window.context.tsx, src/screens/swap.screen.tsx, src/util/utils.ts
* fix blankedAddress overflow 
* group receiver-addresses in swap screen by blockchain
=> [NO-TASK] small improvements (#319)

package-lock.json, package.json, src/components/info-banner.tsx, src/components/layout.tsx, src/hooks/store.hook.ts
- [DEV-2752] integrate info banner
[DEV-2752]: https://dfxswiss.atlassian.net/browse/DEV-2752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2752] integrate info banner

src/screens/sell-info.screen.tsx
- [DEV-2889] remove beneficiary name copy button
[DEV-2889]: https://dfxswiss.atlassian.net/browse/DEV-2889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2889] remove beneficiary name copy button

src/components/navigation.tsx
- [DEV-2866] fix title overflow (+ reduce clickable area of back button)
[DEV-2866]: https://dfxswiss.atlassian.net/browse/DEV-2866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2866] fix title overflow

src/hooks/kyc-helper.hook.ts, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2937](https://dfxswiss.atlassian.net/browse/DEV-2937) Change "stock register" to "shareholder register"
[DEV-2937]: https://dfxswiss.atlassian.net/browse/DEV-2937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2937] Shareholder register

src/components/home/settings-overlays.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2913](https://dfxswiss.atlassian.net/browse/DEV-2913) remove "deletion is irreversible" sentence
[DEV-2913]: https://dfxswiss.atlassian.net/browse/DEV-2913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2913] account deletion warning message

src/screens/account.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2912](https://dfxswiss.atlassian.net/browse/DEV-2912) rearrange account screen content
- [DEV-2911](https://dfxswiss.atlassian.net/browse/DEV-2911) remove "copy address" component
- [DEV-2914](https://dfxswiss.atlassian.net/browse/DEV-2914) remove "Settings" button
[DEV-2912]: https://dfxswiss.atlassian.net/browse/DEV-2912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2911]: https://dfxswiss.atlassian.net/browse/DEV-2911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2914]: https://dfxswiss.atlassian.net/browse/DEV-2914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2912] [DEV-2911] [DEV-2914] Account screen layout

src/screens/payment-routes.screen.tsx
- [DEV-2960] Select Route ID using Dropdown
[DEV-2960]: https://dfxswiss.atlassian.net/browse/DEV-2960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2960] Select Route ID using Dropdown

package-lock.json, package.json, src/hooks/kyc-helper.hook.ts, src/screens/kyc.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/support-issue.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2960] Minor improvements
[DEV-2960]: https://dfxswiss.atlassian.net/browse/DEV-2960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2960] Minor improvements

package-lock.json, package.json, src/hooks/kyc-helper.hook.ts, src/screens/kyc.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/support-issue.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2960] select Route ID using dropdown
- [DEV-2956] Minor improvements
[DEV-2960]: https://dfxswiss.atlassian.net/browse/DEV-2960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2956]: https://dfxswiss.atlassian.net/browse/DEV-2956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2960], [DEV-2956]

src/screens/payment-link.screen.tsx
- [DEV-2970] LNURL super-link support
- [DEV-2972] reload on no pending payment error message
[DEV-2970]: https://dfxswiss.atlassian.net/browse/DEV-2970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2972]: https://dfxswiss.atlassian.net/browse/DEV-2972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2970] LNURL super-link support

src/screens/payment-routes.screen.tsx
- [DEV-2962](https://dfxswiss.atlassian.net/browse/DEV-2962) Remove Payment LNURL details
=> [DEV-2962] Remove Payment LNURL details

src/screens/payment-routes.screen.tsx
- [DEV-2962] remove Payment LNURL details
=> [DEV-2962] remove Payment LNURL details (#345)

src/contexts/wallet.context.tsx, src/hooks/wallets/metamask.hook.ts, src/screens/account.screen.tsx, src/screens/settings.screen.tsx
- [DEV-2946] fix account switch bug
[DEV-2946]: https://dfxswiss.atlassian.net/browse/DEV-2946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2946] fix account switch bug

src/screens/support-issue.screen.tsx
- [DEV-2985] remove redundant free text field for limit request
[DEV-2985]: https://dfxswiss.atlassian.net/browse/DEV-2985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2985] remove redundant free text field for limit request

src/screens/payment-link.screen.tsx
- [DEV-2992] display ethereum uri
[DEV-2992]: https://dfxswiss.atlassian.net/browse/DEV-2992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2992] display ethereum uri

src/App.tsx, src/util/lnurl.ts
- [DEV-2961] shorten LNURLs with redirect
[DEV-2961]: https://dfxswiss.atlassian.net/browse/DEV-2961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2961] shorten LNURLs

package-lock.json, package.json, src/App.tsx, src/screens/payment-link.screen.tsx, src/screens/payment-routes.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/lnurl.ts
- [NO-TASK] fix disabled route ID selection in payment links form
- [NO-TASK] check Payment Link permission
- [DEV-2983] add payment method dropdown for payment links
- [DEV-2961] shorten LNURLs 
[DEV-2983]: https://dfxswiss.atlassian.net/browse/DEV-2983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2961]: https://dfxswiss.atlassian.net/browse/DEV-2961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2983], [DEV-2961], [NO-TASK] Payment Link related improvements & fixes

src/screens/payment-link.screen.tsx
- [DEV-2998] add FrankencoinPay.com to payment methods
[DEV-2998]: https://dfxswiss.atlassian.net/browse/DEV-2998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2998] add FrankencoinPay.com to payment methods

src/components/home/wallet/connect-taro.tsx, src/components/home/wallet/connect-wallet-connect.tsx, src/components/payment/payment-info-sell.tsx, src/components/payment/qr-code.tsx, src/screens/payment-link.screen.tsx, src/screens/payment-routes.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3007] remove copy icon & label from Payment Link QR-Code
[DEV-3007]: https://dfxswiss.atlassian.net/browse/DEV-3007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3007] remove copy icon & label from Payment Link QR-Code

src/screens/payment-link.screen.tsx
- [DEV-2997] remove "Payment method" label
[DEV-2997]: https://dfxswiss.atlassian.net/browse/DEV-2997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2997] Remove "Payment method" label

src/screens/payment-link.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [NO-TASK] adopt new JSON response format
=> [NO-TASK] adopt new JSON response format

src/screens/payment-link.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3006] payment link redesign
[DEV-3006]: https://dfxswiss.atlassian.net/browse/DEV-3006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3006] payment link redesign

src/screens/payment-link.screen.tsx
- [DEV-3010] design touch up
[DEV-3010]: https://dfxswiss.atlassian.net/browse/DEV-3010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3010] design touch up

src/screens/payment-routes.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2959] improve expiry time selection
[DEV-2959]: https://dfxswiss.atlassian.net/browse/DEV-2959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2959] improve expiry time selection

src/screens/payment-link.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
* [NO-TASK] list recommended wallets
* [NO-TASK] minor font adjustment
* [NO-TASK] minor layout adjustments
=> [NO-TASK] list recommended wallets (#369)

src/screens/payment-routes.screen.tsx
- [DEV-3017] fix missing recipient email
[DEV-3017]: https://dfxswiss.atlassian.net/browse/DEV-3017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3017] fix missing recipient email

src/screens/payment-link.screen.tsx, src/screens/payment-routes.screen.tsx, src/util/utils.ts
- [DEV-3018] extend payment link details
[DEV-3018]: https://dfxswiss.atlassian.net/browse/DEV-3018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3018] extend payment link details

src/screens/payment-routes.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/utils.ts
- [DEV-3019] optimise Payment Link layout
[DEV-3019]: https://dfxswiss.atlassian.net/browse/DEV-3019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3019] optimise Payment Link layout

src/components/layout.tsx, src/components/navigation.tsx, src/screens/payment-link.screen.tsx
- [DEV-2996] show small nav menu under /payment-link
[DEV-2996]: https://dfxswiss.atlassian.net/browse/DEV-2996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2996] show small nav menu under /payment-link

package-lock.json, package.json, src/screens/payment-link.screen.tsx
- [DEV-3023] adjust recipient details
[DEV-3023]: https://dfxswiss.atlassian.net/browse/DEV-3023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3023] adjust recipient details

package-lock.json, package.json, src/components/layout.tsx, src/components/navigation.tsx, src/screens/payment-link.screen.tsx
- [DEV-2996] show small nav menu under /payment-link
- [DEV-3023] adjust recipient details
[DEV-2996]: https://dfxswiss.atlassian.net/browse/DEV-2996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3023]: https://dfxswiss.atlassian.net/browse/DEV-3023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2996], [DEV-3023] 

package-lock.json, package.json, src/components/home/settings-overlays.tsx, src/components/overlays.tsx, src/screens/payment-routes.screen.tsx, src/screens/settings.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2694] add delete button to payment routes
[DEV-2694]: https://dfxswiss.atlassian.net/browse/DEV-2694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2694] add delete button to payment routes

src/screens/support-issue.screen.tsx
- [DEV-2982] add back "transaction missing" button
[DEV-2982]: https://dfxswiss.atlassian.net/browse/DEV-2982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2982] add back "transaction missing" button

package-lock.json, package.json, src/screens/payment-link.screen.tsx, src/screens/sell.screen.tsx
- [DEV-3039] minor QR Code updates
[DEV-3039]: https://dfxswiss.atlassian.net/browse/DEV-3039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3039] minor QR Code updates

package-lock.json, package.json, src/App.tsx, src/screens/buy.screen.tsx, src/screens/payment-link.screen.tsx, src/screens/sell.screen.tsx, src/screens/support-issue.screen.tsx
- [DEV-2982] Add back "transaction missing" button
- [DEV-3039] Minor QR Code updates
- [NO-TASK] Spend-Get flow changes
- [NO-TASK] Minor fixes 
[DEV-2982]: https://dfxswiss.atlassian.net/browse/DEV-2982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3039]: https://dfxswiss.atlassian.net/browse/DEV-3039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2982], [DEV-3039], [NO-TASK]

package-lock.json, package.json, src/config/labels.ts, src/screens/support-issue.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3044] add "Notification of changes" support issue type
[DEV-3044]: https://dfxswiss.atlassian.net/browse/DEV-3044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3044] add "Notification of changes" support issue type

package-lock.json, package.json, src/config/labels.ts, src/screens/support-issue.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3044] add "Notification of changes" support issue type  
- [NO-TASK] add missing TX button back to TX-screen 
[DEV-3044]: https://dfxswiss.atlassian.net/browse/DEV-3044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3044], [NO-TASK] add "Missing Tx" button back to Tx-screen

src/components/payment/qr-code.tsx, src/screens/payment-link.screen.tsx
[DEV-2779] dynamic payment link urls
[DEV-2779]: https://dfxswiss.atlassian.net/browse/DEV-2779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2779] dynamic payment link urls

src/components/payment/qr-code.tsx, src/screens/kyc.screen.tsx, src/screens/payment-link.screen.tsx
- [DEV-2779] dynamic payment link urls
- [DEV-3011] Link to "Notification of Changes" support in KYC process
[DEV-2779]: https://dfxswiss.atlassian.net/browse/DEV-2779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3011]: https://dfxswiss.atlassian.net/browse/DEV-3011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2779], [DEV-3011]

src/contexts/app-handling.context.tsx, src/index-widget.tsx, src/screens/payment-link.screen.tsx
- [DEV-3090] add lightning to AppParams
[DEV-3090]: https://dfxswiss.atlassian.net/browse/DEV-3090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3090] add lightning to AppParams

src/contexts/settings.context.tsx, src/screens/kyc.screen.tsx, src/screens/support-issue.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3079] limit file types to PDF and images
[DEV-3079]: https://dfxswiss.atlassian.net/browse/DEV-3079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3079] limit file types to PDF and images

src/contexts/app-handling.context.tsx, src/contexts/settings.context.tsx, src/index-widget.tsx, src/screens/kyc.screen.tsx, src/screens/payment-link.screen.tsx, src/screens/support-issue.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3079] limit file types to PDF and images
- [DEV-3090] add lightning to AppParams 
- [NO-TASK] Nationality hint 
[DEV-3079]: https://dfxswiss.atlassian.net/browse/DEV-3079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3090]: https://dfxswiss.atlassian.net/browse/DEV-3090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3079], [DEV-3090], [NO-TASK]

src/App.tsx, src/contexts/settings.context.tsx, src/hooks/guard.hook.ts, src/screens/sepa.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2950] basic XML file data upload form
[DEV-2950]: https://dfxswiss.atlassian.net/browse/DEV-2950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2950] basic XML file data upload form

src/App.tsx, src/contexts/settings.context.tsx, src/hooks/guard.hook.ts, src/screens/payment-link.screen.tsx, src/screens/sepa.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2950] SEPA file upload screen
- [NO-TASK] Wallet list adjusted 
[DEV-2950]: https://dfxswiss.atlassian.net/browse/DEV-2950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2950] SEPA file upload screen + Wallet list adjusted 

src/components/payment/qr-code.tsx, src/config/payment-link-wallets.ts, src/screens/payment-link.screen.tsx, src/screens/payment-routes.screen.tsx
- [DEV-3099] Minor Payment Link Screen improvements
- [DEV-3103] Integrate `displayQr` config
- [DEV-3106] Improve pending payment UI
- [DEV-3115] Move Payment Link wallet definitions to separate config file
[DEV-3099]: https://dfxswiss.atlassian.net/browse/DEV-3099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3103]: https://dfxswiss.atlassian.net/browse/DEV-3103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3106]: https://dfxswiss.atlassian.net/browse/DEV-3106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3115]: https://dfxswiss.atlassian.net/browse/DEV-3115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
=> [DEV-3106][DEV-3103][DEV-3115][DEV-3099] Payment Link screen updates

package-lock.json, package.json, src/App.tsx, src/screens/account.screen.tsx, src/screens/buy.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/sell.screen.tsx
* [DEV-3119](https://dfxswiss.atlassian.net/browse/DEV-3119) Small improvements
[DEV-3119]: https://dfxswiss.atlassian.net/browse/DEV-3119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3119] small improvements

package-lock.json, package.json, src/App.tsx, src/components/payment/qr-code.tsx, src/config/payment-link-wallets.ts, src/screens/account.screen.tsx, src/screens/buy.screen.tsx, src/screens/chat.screen.tsx, src/screens/payment-link.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/sell.screen.tsx, src/screens/support-issue.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/utils.ts
- [DEV-2825] Support Chat
- [DEV-3099] Minor Payment Link Screen improvements
- [DEV-3103] Integrate `displayQr` config
- [DEV-3106] Improve pending payment UI
- [DEV-3115] Move Payment Link wallet definitions to separate config file
- [DEV-3119] Small improvements in Services
[DEV-3099]: https://dfxswiss.atlassian.net/browse/DEV-3099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3103]: https://dfxswiss.atlassian.net/browse/DEV-3103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3106]: https://dfxswiss.atlassian.net/browse/DEV-3106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3115]: …
=> [DEV-3106], [DEV-3103], [DEV-3115], [DEV-3099], [DEV-3119], [DEV-2825]

src/App.tsx, src/config/payment-link-wallets.ts
- [DEV-3086] redirect Payment Link URLs to /pl
[DEV-3086]: https://dfxswiss.atlassian.net/browse/DEV-3086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3086] redirect Payment Link URLs to /pl

src/components/info-banner.tsx
* [DEV-3113] change info banner color
[DEV-3113]: https://dfxswiss.atlassian.net/browse/DEV-3113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3113] change info banner color

src/screens/payment-link.screen.tsx
* [DEV-3102] fix wallet icon grid in widget mode
[DEV-3102]: https://dfxswiss.atlassian.net/browse/DEV-3102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3102] fix wallet icon grid in widget mode

src/config/payment-link-wallets.ts, src/screens/payment-link.screen.tsx
* [DEV-3105] integrate payment link standard
[DEV-3105]: https://dfxswiss.atlassian.net/browse/DEV-3105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3105] integrate payment link standard

package-lock.json, package.json, src/App.tsx, src/components/info-banner.tsx, src/config/payment-link-wallets.ts, src/screens/buy.screen.tsx, src/screens/chat.screen.tsx, src/screens/payment-link.screen.tsx, src/screens/sell.screen.tsx, src/util/lnurl.ts
- [DEV-3086] redirect Payment Link URLs to /pl
- [DEV-3102] fix wallet icon grid in widget mode
- [DEV-3105] integrate payment link standard 
- [DEV-3113] change info banner color
- [NO-TASK] adjust payment-info update logic + chat screen UX
[DEV-3086]: https://dfxswiss.atlassian.net/browse/DEV-3086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3113]: https://dfxswiss.atlassian.net/browse/DEV-3113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3102]: https://dfxswiss.atlassian.net/browse/DEV-3102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3105]: https://dfxswiss.atlassian.net/browse/DEV-3105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
=> [DEV-3086], [DEV-3102], [DEV-3105], [DEV-3113], [NO-TASK] adjust payment-info update logic + chat screen UX

src/screens/payment-link.screen.tsx
- [DEV-3150] show supported wallet for pending payment
[DEV-3150]: https://dfxswiss.atlassian.net/browse/DEV-3150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3150] show supported wallet for pending payment

package-lock.json, package.json, src/App.tsx, src/screens/chat.screen.tsx, src/screens/payment-link.screen.tsx, src/screens/support-issue.screen.tsx
- [DEV-3150] show supported wallet for pending payment
- [NO-TASK] refactor with support issue UID
[DEV-3150]: https://dfxswiss.atlassian.net/browse/DEV-3150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3150], [NO-TASK] support issue UID

src/screens/transaction.screen.tsx
- [DEV-3049] hide cointracking button if "Account" role
[DEV-3049]: https://dfxswiss.atlassian.net/browse/DEV-3049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3049] hide cointracking button if "Account" role

src/screens/bank-accounts.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2981] directly display add IBAN form
[DEV-2981]: https://dfxswiss.atlassian.net/browse/DEV-2981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2981] directly display add IBAN form

package-lock.json, package.json, src/screens/payment-routes.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3153] enable recipient address edit
[DEV-3153]: https://dfxswiss.atlassian.net/browse/DEV-3153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3153] enable recipient address edit

package-lock.json, package.json, src/components/overlays.tsx, src/config/feature-tree.ts, src/screens/bank-accounts.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/settings.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2981] directly display add IBAN form
- [DEV-3049] Hide CoinTracking button if "Account" role
- [DEV-3093] optionally show disabled wallet + refactor
- [DEV-3097] MATIC -> POL
- [DEV-3153] enable recipient address
- [NO-TASK] Add Frankencoin Base blockchain
[DEV-3049]: https://dfxswiss.atlassian.net/browse/DEV-3049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3097]: https://dfxswiss.atlassian.net/browse/DEV-3097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2981]: https://dfxswiss.atlassian.net/browse/DEV-2981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3093]: https://dfxswiss.atlassian.net/browse/DEV-3093?atlOrigin=eyJpIjoiNWR …
=> [DEV-2981], [DEV-3049], [DEV-3093], [DEV-3097], [DEV-3153], [NO-TASK] add Frankencoin Base blockchain

package-lock.json, package.json, src/App.tsx, src/screens/support-issue.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3130] transaction refund
[DEV-3130]: https://dfxswiss.atlassian.net/browse/DEV-3130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3130] transaction refund

package-lock.json, package.json, src/components/overlays.tsx, src/config/payment-link-wallets.ts, src/hooks/kyc-helper.hook.ts, src/screens/buy.screen.tsx, src/screens/kyc.screen.tsx, src/screens/settings.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2966] & [DEV-2967] integrate two new KYC steps
- [DEV-2980] Business -> organization
- [DEV-3174] replace LNURL with URL
- [DEV-3181] deactivate SEPA-Instant
- [NO-TASK] Update CompatibleWallets
[DEV-3174]: https://dfxswiss.atlassian.net/browse/DEV-3174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2966]: https://dfxswiss.atlassian.net/browse/DEV-2966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2967]: https://dfxswiss.atlassian.net/browse/DEV-2967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2980]: https://dfxswiss.atlassian.net/browse/DEV-2980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
=> [DEV-2966], [DEV-2967], [DEV-2980], [DEV-3174], [DEV-3181], [NO-TASK] Update CompatibleWallets

package-lock.json, package.json, src/App.tsx, src/contexts/app-handling.context.tsx, src/screens/invoice.screen.tsx, src/screens/payment-link.screen.tsx, src/screens/payment-routes.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3162] create /invoice screen
[DEV-3162]: https://dfxswiss.atlassian.net/browse/DEV-3162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3162] create /invoice screen

package-lock.json, package.json, src/App.tsx, src/contexts/app-handling.context.tsx, src/screens/invoice.screen.tsx, src/screens/payment-link.screen.tsx, src/screens/payment-routes.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
* [DEV-3162] create /invoice screen
* [DEV-3188] add optional recipient search param
* [NO-TASK] fix payment-link refetch timeout
* [NO-TASK] fix StyledDataTableRow padding
[DEV-3162]: https://dfxswiss.atlassian.net/browse/DEV-3162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3188]: https://dfxswiss.atlassian.net/browse/DEV-3188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3162]&[DEV-3188] create /invoice screen, [NO-TASK] minor improvements

src/screens/payment-link.screen.tsx
- [DEV-3196] expand payment details for PAY_TO_ADDRESS
[DEV-3196]: https://dfxswiss.atlassian.net/browse/DEV-3196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3196] expand payment details for PAY_TO_ADDRESS

src/screens/payment-link.screen.tsx
- [DEV-3199] display expiry date in payment details
[DEV-3199]: https://dfxswiss.atlassian.net/browse/DEV-3199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3199] display expiry date in payment details

src/screens/invoice.screen.tsx, src/screens/payment-link.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/utils.ts
- [DEV-3193] check invoice link validity
[DEV-3193]: https://dfxswiss.atlassian.net/browse/DEV-3193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3193] check invoice link validity

src/screens/invoice.screen.tsx, src/screens/payment-link.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/utils.ts
- [DEV-3196] expand payment details for PAY_TO_ADDRESS
- [DEV-3199] display expiry date in payment details
[DEV-3196]: https://dfxswiss.atlassian.net/browse/DEV-3196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3199]: https://dfxswiss.atlassian.net/browse/DEV-3199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3196], [DEV-3199]

package-lock.json, package.json, src/hooks/kyc-helper.hook.ts, src/screens/kyc.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2857] add manual Ident form
[DEV-2857]: https://dfxswiss.atlassian.net/browse/DEV-2857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2857] Add manual Ident form

src/screens/payment-link.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/evm-uri.ts
- [DEV-3197] parse and display EVM URI
[DEV-3197]: https://dfxswiss.atlassian.net/browse/DEV-3197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3197] parse and display EVM URI

src/screens/invoice.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3221] improve recipient error message
[DEV-3221]: https://dfxswiss.atlassian.net/browse/DEV-3221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3221] improve recipient error message

package-lock.json, package.json, src/components/payment/add-bank-account.tsx, src/hooks/kyc-helper.hook.ts, src/screens/invoice.screen.tsx, src/screens/kyc.screen.tsx, src/screens/payment-link.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/evm-uri.ts
- [DEV-2857] Add manual Ident form 
- [DEV-3197] Parse and display EVM URI
- [NO-TASK] Display error message on failed add bank account
- [NO-TASK] Add Ident Type to label
[DEV-2857]: https://dfxswiss.atlassian.net/browse/DEV-2857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3197]: https://dfxswiss.atlassian.net/browse/DEV-3197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2857], [DEV-3197], [NO-TASK]

src/screens/payment-link.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3244] add terms & conditions
[DEV-3244]: https://dfxswiss.atlassian.net/browse/DEV-3244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3244] add terms & conditions

package-lock.json, package.json, src/config/labels.ts, src/hooks/session-store.hook.ts, src/screens/bank-accounts.screen.tsx, src/screens/chat.screen.tsx, src/screens/payment-link.screen.tsx, src/screens/sell-info.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3186] enable refund confirmation for BUY transactions
[DEV-3186]: https://dfxswiss.atlassian.net/browse/DEV-3186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3186] enable refund confirmation for BUY transactions

package-lock.json, package.json, src/config/labels.ts, src/hooks/session-store.hook.ts, src/screens/bank-accounts.screen.tsx, src/screens/chat.screen.tsx, src/screens/payment-link.screen.tsx, src/screens/sell-info.screen.tsx, src/screens/tfa.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3186] Enable refund confirmation for BUY transactions
- [DEV-3244] Add terms & conditions 
- [NO-TASK] Fixed TFA error handling
[DEV-3186]: https://dfxswiss.atlassian.net/browse/DEV-3186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3244]: https://dfxswiss.atlassian.net/browse/DEV-3244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3186], [DEV-3244], [NO-TASK] Fixed TFA error handling

src/screens/transaction.screen.tsx
- [NO-TASK] minor improvements
=> [NO-TASK] minor improvements

package-lock.json, package.json, src/config/labels.ts, src/screens/support-issue.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3100] Add "bug report" support issue type
[DEV-3100]: https://dfxswiss.atlassian.net/browse/DEV-3100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3100] add "bug report" support issue type

src/App.tsx, src/contexts/settings.context.tsx, src/hooks/web3.hook.ts, src/screens/blockchain-tx.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/utils.ts
- [DEV-3214] transaction signing
[DEV-3214]: https://dfxswiss.atlassian.net/browse/DEV-3214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3214] transaction signing

package-lock.json, package.json, src/App.tsx, src/config/labels.ts, src/contexts/settings.context.tsx, src/hooks/web3.hook.ts, src/screens/blockchain-tx.screen.tsx, src/screens/support-issue.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/utils.ts
- [DEV-3100] Add "bug report" support issue type
- [DEV-3214] Transaction signing
- [NO-TASK] Improve refund button label
- [NO-TASK] Fix login redirect + IBAN dropdown
- [NO-TASK] improve refund amount display
[DEV-3100]: https://dfxswiss.atlassian.net/browse/DEV-3100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3214]: https://dfxswiss.atlassian.net/browse/DEV-3214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3100], [DEV-3214], [NO-TASK] refund page improvements

src/hooks/countdown.hook.ts, src/screens/payment-link.screen.tsx, src/screens/sell-info.screen.tsx
- [DEV-3243] payment link countdown
[DEV-3243]: https://dfxswiss.atlassian.net/browse/DEV-3243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3243] payment link countdown

src/screens/payment-link.screen.tsx
- [DEV-3209] add visual payment status feedback
[DEV-3209]: https://dfxswiss.atlassian.net/browse/DEV-3209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3209] add visual payment status feedback

package-lock.json, package.json, src/screens/kyc.screen.tsx, src/screens/tfa.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3237] integrate mail 2FA
[DEV-3237]: https://dfxswiss.atlassian.net/browse/DEV-3237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3237] integrate mail 2FA

package-lock.json, package.json, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3258] display chargeback TX and date
[DEV-3258]: https://dfxswiss.atlassian.net/browse/DEV-3258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3258] display chargeback TX and date

README.md, package-lock.json, package.json, src/contexts/app-handling.context.tsx, src/screens/payment-link.screen.tsx, src/screens/sell-info.screen.tsx
- [DEV-3222] payment link redirect on completion
[DEV-3222]: https://dfxswiss.atlassian.net/browse/DEV-3222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3222] payment link redirect on completion

README.md, package-lock.json, package.json, src/contexts/app-handling.context.tsx, src/hooks/countdown.hook.ts, src/screens/kyc.screen.tsx, src/screens/payment-link.screen.tsx, src/screens/sell-info.screen.tsx, src/screens/tfa.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/utils.ts
- [DEV-3209] Add visual payment status feedback
- [DEV-3222] payment link redirect on completion
- [DEV-3237] Integrate mail 2FA 
- [DEV-3242] Adjust URI display 
- [DEV-3243] Payment link countdown
- [DEV-3258] display chargeback TX and date
- [DEV-3278] Make refund button white
- [NO-TASK] Hide IBAN dropdown for checkoutTx transactions
[DEV-3243]: https://dfxswiss.atlassian.net/browse/DEV-3243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3278]: https://dfxswiss.atlassian.net/browse/DEV-3278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3209]: https://dfxswiss.atlassian.net/browse/DEV-3209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> [DEV-3209], [DEV-3222], [DEV-3237], [DEV-3242], [DEV-3243], [DEV-3258], [DEV-3278], [NO-TASK] refund IBAN dropdown update

src/screens/swap.screen.tsx
[DEV-3133] Make amount out editable in swap screen
[DEV-3133]: https://dfxswiss.atlassian.net/browse/DEV-3133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3133] make amount out editable in swap screen

src/screens/buy.screen.tsx, src/screens/sell.screen.tsx, src/screens/swap.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
[DEV-2987] Improve "You get about" label 
[DEV-2987]: https://dfxswiss.atlassian.net/browse/DEV-2987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-2987] improve "You get about" label

src/screens/account-merge.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3094] improve user feedback in account-merge screen
[DEV-3094]: https://dfxswiss.atlassian.net/browse/DEV-3094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3094] improve user feedback in account-merge screen

src/config/feature-tree.ts, src/hooks/navigation.hook.ts, src/screens/bank-accounts.screen.tsx, src/screens/settings.screen.tsx, src/screens/support-issue.screen.tsx, src/screens/transaction.screen.tsx
- [DEV-3289] Activate Monero sell
[DEV-3289]: https://dfxswiss.atlassian.net/browse/DEV-3289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3289] activate Monero sell

package-lock.json, package.json, src/config/feature-tree.ts, src/hooks/navigation.hook.ts, src/screens/account-merge.screen.tsx, src/screens/bank-accounts.screen.tsx, src/screens/buy.screen.tsx, src/screens/sell.screen.tsx, src/screens/settings.screen.tsx, src/screens/support-issue.screen.tsx, src/screens/swap.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-2987] Improve "You get about" label 
- [DEV-3094] Improve user feedback in account-merge screen 
- [DEV-3133] Make amount out editable in swap screen 
- [DEV-3289] Activate Monero sell 
- [NO-TASK] Fix state in /bank-accounts
- [NO-TASK] add menu to pick CSV export type
[DEV-2987]: https://dfxswiss.atlassian.net/browse/DEV-2987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3094]: https://dfxswiss.atlassian.net/browse/DEV-3094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3133]: https://dfxswiss.atlassian.net/browse/DEV-3133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3289]: …
=> [DEV-2987], [DEV-3094], [DEV-3133], [DEV-3289], [NO-TASK] add CSV export type menu

src/screens/bank-accounts.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/support-issue.screen.tsx, src/screens/transaction.screen.tsx
- [DEV-3293] refactor bank accounts / IBANs
[DEV-3293]: https://dfxswiss.atlassian.net/browse/DEV-3293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3293] refactor bank accounts / IBANs

src/screens/payment-link.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3149] invalid payment link error message
- [DEV-3151] change compatible wallet section header
[DEV-3149]: https://dfxswiss.atlassian.net/browse/DEV-3149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3151]: https://dfxswiss.atlassian.net/browse/DEV-3151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3149] invalid payment link error message

package-lock.json, package.json, src/contexts/settings.context.tsx, src/screens/kyc.screen.tsx, src/screens/payment-routes.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3346] Add birthday to manual ident step
[DEV-3346]: https://dfxswiss.atlassian.net/browse/DEV-3346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3346] Add birthday to manual ident step

src/components/cointracking.tsx, src/components/home/wallet/connect-bitbox.tsx, src/components/home/wallet/connect-ledger.tsx, src/components/home/wallet/connect-trezor.tsx, src/screens/account.screen.tsx, src/screens/blockchain-tx.screen.tsx, src/screens/buy.screen.tsx, src/screens/chat.screen.tsx, src/screens/invoice.screen.tsx, src/screens/kyc.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/sell.screen.tsx, src/screens/settings.screen.tsx, src/screens/support-issue.screen.tsx, src/screens/support-tickets.screen.tsx, src/screens/support.screen.tsx, src/screens/swap.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3301] Fix button color
[DEV-3301]: https://dfxswiss.atlassian.net/browse/DEV-3301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3301] Fix button color

package-lock.json, package.json, src/App.tsx, src/components/cointracking.tsx, src/components/home/wallet/connect-bitbox.tsx, src/components/home/wallet/connect-ledger.tsx, src/components/home/wallet/connect-trezor.tsx, src/contexts/settings.context.tsx, src/screens/account.screen.tsx, src/screens/bank-accounts.screen.tsx, src/screens/blockchain-tx.screen.tsx, src/screens/buy.screen.tsx, src/screens/chat.screen.tsx, src/screens/invoice.screen.tsx, src/screens/kyc.screen.tsx, src/screens/payment-link.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/sell.screen.tsx, src/screens/settings.screen.tsx, src/screens/support-issue.screen.tsx, src/screens/support-tickets.screen.tsx, src/screens/support.screen.tsx, src/screens/swap.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
* [DEV-3149] Invalid payment link error message
* [DEV-3207] Display existing support tickets
* [DEV-3293] Refactor bank accounts / IBANs
* [DEV-3301] Fix button color
* [DEV-3346] Add birthday to manual ident step
* [DEV-3347] EDLC icon
[DEV-3207]: https://dfxswiss.atlassian.net/browse/DEV-3207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3149]: https://dfxswiss.atlassian.net/browse/DEV-3149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3293]: https://dfxswiss.atlassian.net/browse/DEV-3293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3346]: https://dfxswiss.atlassian.net/browse/DEV-3346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
=> [DEV-3149], [DEV-3207], [DEV-3293], [DEV-3301], [DEV-3346], [DEV-3347]

package-lock.json, package.json, src/components/cointracking.tsx, src/components/home/connect-base.tsx, src/components/home/wallet/connect-bitbox.tsx, src/components/home/wallet/connect-cli.tsx, src/components/home/wallet/connect-ledger.tsx, src/components/home/wallet/connect-metamask.tsx, src/components/home/wallet/connect-taro.tsx, src/components/home/wallet/connect-trezor.tsx, src/components/home/wallet/connect-wallet-connect.tsx, src/hooks/wallets/bitbox.hook.ts, src/screens/buy.screen.tsx, src/screens/sell.screen.tsx, src/screens/swap.screen.tsx, src/screens/transaction.screen.tsx, src/util/wallet-switch-error.ts
* [DEV-3308] Enable Swap for BSC & Base
* [NO-TASK] Enable Cointracking for Account role
* [NO-TASK] Fix erroneous logout bug
* [NO-TASK] Redirect to /login on useAddressGuard
[DEV-3308]: https://dfxswiss.atlassian.net/browse/DEV-3308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3308], [NO-TASK] Cointracking for Account role & fix redirect after login

src/components/private-asset-hint.tsx, src/screens/sell.screen.tsx, src/screens/swap.screen.tsx
- [DEV-3357] add private asset checks to sell & swap screens
[DEV-3357]: https://dfxswiss.atlassian.net/browse/DEV-3357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3357] add private asset checks to sell & swap screens

src/App.tsx, src/config/labels.ts, src/screens/kyc-file.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/utils.ts
- [DEV-3081] Add screen for KYC file previews
[DEV-3081]: https://dfxswiss.atlassian.net/browse/DEV-3081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3081] Add screen for KYC file previews

package-lock.json, package.json, src/components/payment/add-bank-account.tsx, src/contexts/settings.context.tsx, src/screens/bank-accounts.screen.tsx, src/screens/kyc.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/sell-info.screen.tsx, src/screens/sell.screen.tsx
- [DEV-3365] integrate allowed country flags
[DEV-3365]: https://dfxswiss.atlassian.net/browse/DEV-3365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3365] integrate allowed country flags

.github/workflows/dev.yml, .github/workflows/pr.yml, .github/workflows/prd.yml, package-lock.json, package.json, src/App.tsx, src/components/info-banner.tsx, src/components/layout.tsx, src/components/navigation.tsx, src/components/payment/add-bank-account.tsx, src/components/private-asset-hint.tsx, src/config/labels.ts, src/contexts/settings.context.tsx, src/custom-service-worker.js, src/hooks/service-worker.hook.ts, src/screens/bank-accounts.screen.tsx, src/screens/kyc-file.screen.tsx, src/screens/kyc.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/sell-info.screen.tsx, src/screens/sell.screen.tsx, src/screens/swap.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/utils.ts, src/version.ts
* [DEV-3081] Add screen for KYC file previews
* [DEV-3354] auto-update services on new version release
* [DEV-3357] add private asset checks to sell & swap screens
* [DEV-3365] integrate allowed country flags
[DEV-3354]: https://dfxswiss.atlassian.net/browse/DEV-3354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3357]: https://dfxswiss.atlassian.net/browse/DEV-3357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3081]: https://dfxswiss.atlassian.net/browse/DEV-3081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3365]: https://dfxswiss.atlassian.net/browse/DEV-3365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> [DEV-3081], [DEV-3354], [DEV-3357], [DEV-3365]

src/App.tsx, src/screens/kyc-file.screen.tsx, src/util/utils.ts
- [DEV-3385] Open file at root domain
[DEV-3385]: https://dfxswiss.atlassian.net/browse/DEV-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3385] Open file at root domain

src/App.tsx, src/screens/download.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3387] File download services
[DEV-3387]: https://dfxswiss.atlassian.net/browse/DEV-3387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3387] File download services

src/screens/download.screen.tsx, src/util/utils.ts
* [DEV-3387] fixes & improvements
[DEV-3387]: https://dfxswiss.atlassian.net/browse/DEV-3387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3387] Fixes & improvements (#493)

package-lock.json, package.json, src/App.tsx, src/components/edit/mail.edit.tsx, src/contexts/settings.context.tsx, src/screens/edit-mail.screen.tsx, src/screens/kyc.screen.tsx, src/screens/link.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/settings.screen.tsx, src/screens/transaction.screen.tsx
- [DEV-3177] Require 2fa & email verification to update email
[DEV-3177]: https://dfxswiss.atlassian.net/browse/DEV-3177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3177] require 2fa & email verification to update email

package-lock.json, package.json, src/App.tsx, src/components/edit/mail.edit.tsx, src/components/error-hint.tsx, src/contexts/settings.context.tsx, src/screens/edit-mail.screen.tsx, src/screens/kyc.screen.tsx, src/screens/link.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/settings.screen.tsx, src/screens/tfa.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
* [DEV-3177] Require 2FA & email verification to update email
[DEV-3177]: https://dfxswiss.atlassian.net/browse/DEV-3177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3177] Require 2FA & email verification to update email (#473)

package-lock.json, package.json, src/components/error-hint.tsx, src/screens/account.screen.tsx, src/screens/blockchain-tx.screen.tsx, src/screens/kyc.screen.tsx
- [DEV-3433] Fix limit-increase button navigation
- [DEV-3435] Fix financial data bug
- [NO-TASK] Fix ethers dependency issue
[DEV-3435]: https://dfxswiss.atlassian.net/browse/DEV-3435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3433]: https://dfxswiss.atlassian.net/browse/DEV-3433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3435], [DEV-3433], [NO-TASK] Bug fixes

package-lock.json, package.json, src/components/error-hint.tsx, src/config/labels.ts, src/config/payment-link-wallets.ts, src/screens/account.screen.tsx, src/screens/blockchain-tx.screen.tsx, src/screens/chat.screen.tsx, src/screens/kyc.screen.tsx, src/screens/payment-link.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/sell-info.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3101] Add form to set payment link config
- [DEV-3435], [DEV-3433] Bug fixes 
- [NO-TASK] Fixed vulnerabilities
[DEV-3101]: https://dfxswiss.atlassian.net/browse/DEV-3101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3435]: https://dfxswiss.atlassian.net/browse/DEV-3435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3433]: https://dfxswiss.atlassian.net/browse/DEV-3433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3101], [DEV-3433], [DEV-3435], [NO-TASK] Bug fixes

package-lock.json, package.json, src/components/exchange-rate.tsx, src/components/kyc-hint.tsx, src/config/labels.ts, src/contexts/settings.context.tsx, src/contexts/wallet.context.tsx, src/screens/buy-info.screen.tsx, src/screens/buy.screen.tsx, src/screens/kyc.screen.tsx, src/screens/payment-routes.screen.tsx, src/screens/sell-info.screen.tsx, src/screens/sell.screen.tsx, src/screens/swap.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3371] Transaction status support button 
- [DEV-3412] [DEV-3414] [DEV-3424] [DEV-3426] DTO changes
- [DEV-3445]  Payment Link config improvements
- [DEV-3478] ZCHF logo update
[DEV-3371]: https://dfxswiss.atlassian.net/browse/DEV-3371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3412]: https://dfxswiss.atlassian.net/browse/DEV-3412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3414]: https://dfxswiss.atlassian.net/browse/DEV-3414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3424]: https://dfxswiss.atlassian.net/browse/DEV-3424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> [DEV-3371], [DEV-3412], [DEV-3414], [DEV-3424], [DEV-3426], [DEV-3445], [DEV-3478]

package-lock.json, package.json, src/screens/transaction.screen.tsx
- [DEV-3508] Show refund and support buttons on limit exceeded status
- [DEV-3510] Show input amount from refund data
[DEV-3508]: https://dfxswiss.atlassian.net/browse/DEV-3508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3510]: https://dfxswiss.atlassian.net/browse/DEV-3510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3508], [DEV-3510]

package-lock.json, package.json, src/hooks/kyc-helper.hook.ts, src/screens/kyc.screen.tsx
* [DEV-3475] sumsub video ident
[DEV-3475]: https://dfxswiss.atlassian.net/browse/DEV-3475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3475] Basic sumsub video ident setup (#509)

package-lock.json, package.json, src/config/labels.ts, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3498] Integrate TransactionFailureReason.MISSING_LIQUIDITY
[DEV-3498]: https://dfxswiss.atlassian.net/browse/DEV-3498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3498] Integrate TransactionFailureReason.MISSING_LIQUIDITY

package-lock.json, package.json, src/config/labels.ts, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3506] new DataRequest support issue reason
[DEV-3506]: https://dfxswiss.atlassian.net/browse/DEV-3506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3506] new DataRequest support issue reason

package-lock.json, package.json, src/components/home/connect-wrapper.tsx, src/components/home/install-hint.tsx, src/components/home/wallet/connect-address.tsx, src/components/kyc-hint.tsx, src/config/labels.ts, src/contexts/settings.context.tsx, src/contexts/wallet.context.tsx, src/hooks/guard.hook.ts, src/screens/account.screen.tsx, src/screens/chat.screen.tsx, src/screens/home.screen.tsx, src/screens/kyc.screen.tsx, src/screens/support-issue.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- [DEV-3392] Address addition
- [DEV-3498] Integrate TransactionFailureReason.MISSING_LIQUIDITY
- [DEV-3506] New DataRequest support issue reason
- [NO-TASK] Map ident types (ident/video -> ident/sumsubVideo, ident/auto -> ident/sumsubAuto)
- [NO-TASK] Show refund button for LimitExceeded under /tx
[DEV-3392]: https://dfxswiss.atlassian.net/browse/DEV-3392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3498]: https://dfxswiss.atlassian.net/browse/DEV-3498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3506]: https://dfxswiss.atlassian.net/browse/DEV-3506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3392], [DEV-3498], [DEV-3506], [NO-TASK] map ident types, refund button for LimitExceeded

package-lock.json, package.json, src/hooks/wallets/ledger.hook.ts, src/screens/kyc.screen.tsx, src/screens/support-issue.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
* [DEV-3631] Add ledger default error
* [DEV-3631] Adapt message
---------
Co-authored-by: Kolibri <>
[DEV-3631]: https://dfxswiss.atlassian.net/browse/DEV-3631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3631]: https://dfxswiss.atlassian.net/browse/DEV-3631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3631] Add ledger default error (#525)

src/hooks/tx-helper.hook.ts
=> [NO-TASK] Add default undefined and getAddressBalance to hardware wallet

package-lock.json, package.json, src/screens/payment-routes.screen.tsx, src/util/utils.ts
* [DEV-3875] payment link config improvements
* [DEV-3875] fixes
* fixes 2
* [DEV-3875] update packages
[DEV-3875]: https://dfxswiss.atlassian.net/browse/DEV-3875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3875]: https://dfxswiss.atlassian.net/browse/DEV-3875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3875]: https://dfxswiss.atlassian.net/browse/DEV-3875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3875] Payment Link config improvements (#560)

src/screens/payment-routes.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/utils.ts
* [DEV-3875] fix pl config update payload
* [DEV-3875][DEV-3911] fix config updates, remove FrankencoinPay
* [DEV-3911] update packages
[DEV-3875]: https://dfxswiss.atlassian.net/browse/DEV-3875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3875]: https://dfxswiss.atlassian.net/browse/DEV-3875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3911]: https://dfxswiss.atlassian.net/browse/DEV-3911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3875] fix pl config update payload (#568)

package-lock.json, package.json, src/contexts/wallet.context.tsx, src/screens/account-merge.screen.tsx, src/screens/home.screen.tsx
- Await https://github.com/DFXswiss/packages/pull/96
=> [DEV-3937] Fix merge bug

package-lock.json, package.json, src/components/safe/button-group.tsx, src/components/safe/chart.tsx, src/components/safe/portfolio.tsx, src/hooks/safe.hook.ts, src/screens/safe.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json, src/util/utils.ts
* [DEV-3888] add chart & currency switcher
* [DEV-3888] cleanup
* [DEV-3888] cleanup 2
* [DEV-3888] cleanup 3
* [DEV-3888] hide chart if insufficient data
* [DEV-3888] improvements & fixes
* [DEV-3888] cleanup
* [DEV-3888] cleanup
[DEV-3888]: https://dfxswiss.atlassian.net/browse/DEV-3888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3888]: https://dfxswiss.atlassian.net/browse/DEV-3888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3888]: https://dfxswiss.atlassian.net/browse/DEV-3888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3888]: https://dfxswiss.atlassian.net/browse/DEV-3888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
=> [DEV-3888] add chart & currency switcher (#576)

src/config/payment-link-wallets.ts, src/contexts/app-handling.context.tsx, src/contexts/payment-link.context.tsx, src/dto/payment-link.dto.ts, src/hooks/useWalletInfoOptions.ts, src/screens/payment-link.screen.tsx
- Added Muun the list, it works querying the PR directly as it is not 100% compatible with our LNURLs.
- Deeplinking logic is growing in complexity so I moved it out into a new hook.
- Redirection was too fast, the completion screen is almost not noticeable, added 2 secs delay.
=> [DEV-4017]: Muun wallet

src/App.tsx, src/components/circular-countdown.tsx, src/contexts/app-handling.context.tsx, src/contexts/payment-link.context.tsx, src/dto/payment-link.dto.ts, src/hooks/app-params.hook.ts, src/index-widget.tsx, src/screens/payment-link-manage.screen.tsx, src/screens/payment-link-pos.screen.tsx
https://github.com/user-attachments/assets/4d39e474-72d7-4be0-9643-254923e79f97
=> [NO-TASK]: Manage payment link with access key

package-lock.json, package.json, src/config/labels.ts, src/screens/account.screen.tsx, src/screens/buy.screen.tsx, src/screens/support-issue.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
* [DEV-3603] Using TX UID (TODO: packages)
* [DEV-3603] Added confirm endpoint
* [DEV-3603] UI fix
* [DEV-3603] Scroll fix
[DEV-3603]: https://dfxswiss.atlassian.net/browse/DEV-3603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3603]: https://dfxswiss.atlassian.net/browse/DEV-3603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3603]: https://dfxswiss.atlassian.net/browse/DEV-3603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3603]: https://dfxswiss.atlassian.net/browse/DEV-3603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-3603] Buy confirms (#625)

src/dto/payment-link.dto.ts, src/screens/payment-link.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
Depends on https://github.com/DFXswiss/api/pull/2231
=> [DEV-3990]: Public payment link

package-lock.json, package.json, src/hooks/kyc-helper.hook.ts, src/screens/kyc.screen.tsx, src/screens/payment-routes.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
=> KYC updates

src/hooks/payment-link-wallets.hook.ts, src/screens/payment-link.screen.tsx
[DEV-4169]: Public Link UI Improvement
[DEV-4169]: https://dfxswiss.atlassian.net/browse/DEV-4169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-4169]: Public Link UI Improvement

src/components/navigation-link.tsx, src/contexts/app-handling.context.tsx, src/contexts/payment-link-pos.context.tsx, src/contexts/payment-link.context.tsx, src/hooks/navigation.hook.ts, src/hooks/session-store.hook.ts, src/index-widget.tsx, src/screens/payment-link-pos.screen.tsx, src/screens/payment-link.screen.tsx, src/util/utils.ts
- **[NO-TASK] improve formatting**
- **[NO-TASK] refactor lightning param**
=> [NO-TASK] improve amount formatting, refactor lightning param & preserve /pos url params

package-lock.json, package.json, src/App.tsx, src/components/actionable-list.tsx, src/components/navigation.tsx, src/components/pl/payment-status-tile.tsx, src/config/labels.ts, src/screens/chat.screen.tsx, src/screens/payment-link-result.screen.tsx, src/screens/payment-link.screen.tsx, src/screens/settings.screen.tsx, src/screens/swap.screen.tsx, src/screens/transaction.screen.tsx, src/translations/languages/de.json, src/translations/languages/fr.json, src/translations/languages/it.json
- Replace border-1 drop-shadow-md with proper Tailwind classes
- Add fixed overlay for proper menu closing behavior
- Prevent event propagation to avoid unwanted menu closes
- Add rounded corners for better visual appearance
- Fix vertical line artifact that remained after menu close
=> Fix burger menu border artifact issue (#697)
